name: Ranveer Aggarwal
description: Programmer. Reader. Explorer.
meta_description: "Ranveer Aggarwal's Web Space."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
baseurl: /
domain_name: "http://ranveeraggarwal.com"
google_analytics: "UA-74279105-1"
plugins: [jekyll-paginate]
permalink: /:categories/:title

# Details for the RSS feed generator
url: "http://ranveeraggarwal.com"
author: "Ranveer Aggarwal"

# Disqus config
disqus-shortname: "ranveeraggarwal"
